ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM registry.cn-shanghai.aliyuncs.com/public-namespace/kibana:${ELK_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
