ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM registry.cn-shanghai.aliyuncs.com/public-namespace/elasticsearch:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
